const vendors = {
  sot: [
    {
      name: "Базовый",
      description: "Сбалансированный уровень для типовых задач видеонаблюдения.",
      qualityCoefficient: 1.0,
      equipmentPriceIndex: 1.0,
      cableCoefficient: 1.0,
      installationSpeed: 1.0,
      technicalParameters: { maxDistance: 350, efficiency: 0.82, integrationComplexity: 1.0 },
    },
    {
      name: "Hikvision",
      description: "Широкая линейка оборудования и аналитики, умеренно выше по стоимости.",
      qualityCoefficient: 1.08,
      equipmentPriceIndex: 1.12,
      cableCoefficient: 1.01,
      installationSpeed: 1.04,
      technicalParameters: { maxDistance: 420, efficiency: 0.88, integrationComplexity: 1.05 },
    },
    {
      name: "Dahua",
      description: "Оптимальный баланс цены и функциональности.",
      qualityCoefficient: 1.03,
      equipmentPriceIndex: 1.05,
      cableCoefficient: 1.0,
      installationSpeed: 1.03,
      technicalParameters: { maxDistance: 400, efficiency: 0.86, integrationComplexity: 1.03 },
    },
    {
      name: "TRASSIR",
      description: "Сильная видеоаналитика и интеграционный контур, стоимость выше среднего.",
      qualityCoefficient: 1.12,
      equipmentPriceIndex: 1.18,
      cableCoefficient: 1.03,
      installationSpeed: 0.97,
      technicalParameters: { maxDistance: 440, efficiency: 0.9, integrationComplexity: 1.12 },
    },
    {
      name: "Axis",
      description: "Премиальный сегмент с высокой надежностью и расширенной функциональностью.",
      qualityCoefficient: 1.2,
      equipmentPriceIndex: 1.34,
      cableCoefficient: 1.04,
      installationSpeed: 0.95,
      technicalParameters: { maxDistance: 460, efficiency: 0.92, integrationComplexity: 1.15 },
    },
    {
      name: "Uniview",
      description: "Стабильный средний сегмент видеонаблюдения с фокусом на цену/качество.",
      qualityCoefficient: 1.06,
      equipmentPriceIndex: 1.09,
      cableCoefficient: 1.01,
      installationSpeed: 1.01,
      technicalParameters: { maxDistance: 415, efficiency: 0.87, integrationComplexity: 1.04 },
    },
  ],
  sots: [
    {
      name: "Базовый",
      description: "Базовый сценарий СОТС для коммерческой недвижимости.",
      qualityCoefficient: 1.0,
      equipmentPriceIndex: 1.0,
      cableCoefficient: 1.0,
      installationSpeed: 1.0,
      technicalParameters: { maxDistance: 280, efficiency: 0.8, integrationComplexity: 1.0 },
    },
    {
      name: "Бастион",
      description: "Надежный массовый сегмент для типовых задач охранной сигнализации.",
      qualityCoefficient: 1.02,
      equipmentPriceIndex: 1.04,
      cableCoefficient: 1.0,
      installationSpeed: 1.03,
      technicalParameters: { maxDistance: 300, efficiency: 0.83, integrationComplexity: 1.02 },
    },
    {
      name: "Рубеж",
      description: "Умеренно расширенные возможности и интеграция со смежными подсистемами.",
      qualityCoefficient: 1.06,
      equipmentPriceIndex: 1.1,
      cableCoefficient: 1.02,
      installationSpeed: 0.99,
      technicalParameters: { maxDistance: 330, efficiency: 0.86, integrationComplexity: 1.07 },
    },
    {
      name: "Болид",
      description: "Широкая экосистема, удобная интеграция и стабильная поддержка.",
      qualityCoefficient: 1.08,
      equipmentPriceIndex: 1.12,
      cableCoefficient: 1.03,
      installationSpeed: 0.97,
      technicalParameters: { maxDistance: 340, efficiency: 0.87, integrationComplexity: 1.09 },
    },
  ],
  skud: [
    {
      name: "Базовый",
      description: "Базовый уровень СКУД без углубленной аналитики доступа.",
      qualityCoefficient: 1.0,
      equipmentPriceIndex: 1.0,
      cableCoefficient: 1.0,
      installationSpeed: 1.0,
      technicalParameters: { maxDistance: 180, efficiency: 0.79, integrationComplexity: 1.0 },
    },
    {
      name: "Sigur",
      description: "Гибкий функционал, развитая логика доступа и удобный интерфейс.",
      qualityCoefficient: 1.09,
      equipmentPriceIndex: 1.14,
      cableCoefficient: 1.02,
      installationSpeed: 0.98,
      technicalParameters: { maxDistance: 210, efficiency: 0.86, integrationComplexity: 1.1 },
    },
    {
      name: "Parsec",
      description: "Enterprise-профиль и расширенная интеграция с ИТ-инфраструктурой.",
      qualityCoefficient: 1.1,
      equipmentPriceIndex: 1.16,
      cableCoefficient: 1.03,
      installationSpeed: 0.96,
      technicalParameters: { maxDistance: 220, efficiency: 0.88, integrationComplexity: 1.12 },
    },
    {
      name: "PERCo",
      description: "Надежные контроллеры и турникетные решения для поточных объектов.",
      qualityCoefficient: 1.08,
      equipmentPriceIndex: 1.13,
      cableCoefficient: 1.02,
      installationSpeed: 0.97,
      technicalParameters: { maxDistance: 215, efficiency: 0.87, integrationComplexity: 1.1 },
    },
    {
      name: "Biosmart",
      description: "Биометрический контур с повышенными требованиями к настройке.",
      qualityCoefficient: 1.14,
      equipmentPriceIndex: 1.22,
      cableCoefficient: 1.03,
      installationSpeed: 0.93,
      technicalParameters: { maxDistance: 230, efficiency: 0.9, integrationComplexity: 1.16 },
    },
    {
      name: "RusGuard",
      description: "Интеграционный профиль для распределённых объектов и территориального доступа.",
      qualityCoefficient: 1.11,
      equipmentPriceIndex: 1.17,
      cableCoefficient: 1.02,
      installationSpeed: 0.95,
      technicalParameters: { maxDistance: 225, efficiency: 0.88, integrationComplexity: 1.13 },
    },
  ],
  ssoi: [
    {
      name: "Базовый",
      description: "Базовый контур ССОИ с типовой интеграцией подсистем.",
      qualityCoefficient: 1.0,
      equipmentPriceIndex: 1.0,
      cableCoefficient: 1.0,
      installationSpeed: 1.0,
      technicalParameters: { maxDistance: 500, efficiency: 0.8, integrationComplexity: 1.0 },
    },
    {
      name: "TRASSIR",
      description: "Сильная аналитика и интеграция с видеонаблюдением/СКУД.",
      qualityCoefficient: 1.09,
      equipmentPriceIndex: 1.15,
      cableCoefficient: 1.02,
      installationSpeed: 0.99,
      technicalParameters: { maxDistance: 600, efficiency: 0.89, integrationComplexity: 1.13 },
    },
    {
      name: "ISS (Интеллект)",
      description: "Глубокая видеоаналитика и сценарии централизованного мониторинга.",
      qualityCoefficient: 1.12,
      equipmentPriceIndex: 1.2,
      cableCoefficient: 1.03,
      installationSpeed: 0.96,
      technicalParameters: { maxDistance: 640, efficiency: 0.91, integrationComplexity: 1.16 },
    },
    {
      name: "Macroscop",
      description: "Сильный аналитический контур и широкая масштабируемость по объектам.",
      qualityCoefficient: 1.11,
      equipmentPriceIndex: 1.18,
      cableCoefficient: 1.03,
      installationSpeed: 0.97,
      technicalParameters: { maxDistance: 620, efficiency: 0.9, integrationComplexity: 1.14 },
    },
    {
      name: "AxxonSoft",
      description: "Развитая платформа интеграции и видеоаналитики для крупных площадок.",
      qualityCoefficient: 1.13,
      equipmentPriceIndex: 1.22,
      cableCoefficient: 1.03,
      installationSpeed: 0.95,
      technicalParameters: { maxDistance: 640, efficiency: 0.91, integrationComplexity: 1.17 },
    },
  ],
  aps: [
    {
      name: "Базовый",
      description: "Стандартная АПС для типовых объектов без сложных сценариев.",
      qualityCoefficient: 1.0,
      equipmentPriceIndex: 1.0,
      cableCoefficient: 1.0,
      installationSpeed: 1.0,
      technicalParameters: { maxDistance: 260, efficiency: 0.81, integrationComplexity: 1.0 },
    },
    {
      name: "Болид",
      description: "Массовый стандарт АПС с хорошей доступностью и интеграцией.",
      qualityCoefficient: 1.05,
      equipmentPriceIndex: 1.07,
      cableCoefficient: 1.01,
      installationSpeed: 1.01,
      technicalParameters: { maxDistance: 280, efficiency: 0.85, integrationComplexity: 1.05 },
    },
    {
      name: "Рубеж",
      description: "Сбалансированный профиль для адресных и адресно-аналоговых систем.",
      qualityCoefficient: 1.04,
      equipmentPriceIndex: 1.06,
      cableCoefficient: 1.01,
      installationSpeed: 1.0,
      technicalParameters: { maxDistance: 275, efficiency: 0.84, integrationComplexity: 1.04 },
    },
    {
      name: "Аргус-Спектр",
      description: "Специализированные решения, включая радиоканальные сегменты.",
      qualityCoefficient: 1.12,
      equipmentPriceIndex: 1.2,
      cableCoefficient: 0.96,
      installationSpeed: 0.95,
      technicalParameters: { maxDistance: 300, efficiency: 0.9, integrationComplexity: 1.14 },
    },
    {
      name: "Simplex",
      description: "Премиальный международный сегмент для крупных объектов.",
      qualityCoefficient: 1.18,
      equipmentPriceIndex: 1.35,
      cableCoefficient: 1.06,
      installationSpeed: 0.9,
      technicalParameters: { maxDistance: 320, efficiency: 0.92, integrationComplexity: 1.2 },
    },
    {
      name: "Siemens",
      description: "Высоконадежные решения пожарной сигнализации для сложных объектов.",
      qualityCoefficient: 1.16,
      equipmentPriceIndex: 1.28,
      cableCoefficient: 1.04,
      installationSpeed: 0.93,
      technicalParameters: { maxDistance: 315, efficiency: 0.91, integrationComplexity: 1.18 },
    },
  ],
  soue: [
    {
      name: "Базовый",
      description: "Типовая СОУЭ без повышенных требований к акустике.",
      qualityCoefficient: 1.0,
      equipmentPriceIndex: 1.0,
      cableCoefficient: 1.0,
      installationSpeed: 1.0,
      technicalParameters: { maxDistance: 240, efficiency: 0.8, integrationComplexity: 1.0 },
    },
    {
      name: "Болид",
      description: "Надежная массовая линейка для стандартной СОУЭ.",
      qualityCoefficient: 1.03,
      equipmentPriceIndex: 1.05,
      cableCoefficient: 1.01,
      installationSpeed: 1.02,
      technicalParameters: { maxDistance: 255, efficiency: 0.84, integrationComplexity: 1.04 },
    },
    {
      name: "Рубеж",
      description: "Сбалансированный профиль с расширяемым контуром оповещения.",
      qualityCoefficient: 1.04,
      equipmentPriceIndex: 1.08,
      cableCoefficient: 1.02,
      installationSpeed: 1.0,
      technicalParameters: { maxDistance: 265, efficiency: 0.85, integrationComplexity: 1.06 },
    },
    {
      name: "Roxton",
      description: "Премиальная акустика для объектов с высокими требованиями к разборчивости.",
      qualityCoefficient: 1.12,
      equipmentPriceIndex: 1.16,
      cableCoefficient: 1.03,
      installationSpeed: 0.95,
      technicalParameters: { maxDistance: 290, efficiency: 0.9, integrationComplexity: 1.12 },
    },
  ],
};

export function getVendorsBySystem(systemType) {
  return vendors[systemType] || vendors.sot;
}

export function getVendorByName(systemType, vendorName) {
  return getVendorsBySystem(systemType).find((vendor) => vendor.name === vendorName) || getVendorsBySystem(systemType)[0];
}

export function getVendorNames(systemType) {
  return getVendorsBySystem(systemType).map((vendor) => vendor.name);
}

export const MANUFACTURER_SOURCES = {
  sot: {
    Базовый: { website: "https://www.hikvision.com" },
    Hikvision: { website: "https://www.hikvision.com" },
    Dahua: { website: "https://www.dahuasecurity.com" },
    TRASSIR: { website: "https://trassir.com" },
    Axis: { website: "https://www.axis.com" },
    Uniview: { website: "https://global.uniview.com" },
  },
  sots: {
    Базовый: {
      website: "https://shop.bolid.ru",
      searchPathTemplate: "/search/?q={query}",
      preferSearch: true,
    },
    Бастион: { website: "https://bast.ru" },
    Рубеж: {
      website: "https://products.rubezh.ru",
      searchPathTemplate: "/search/?q={query}",
      preferSearch: true,
    },
    Болид: {
      website: "https://shop.bolid.ru",
      searchPathTemplate: "/search/?q={query}",
      preferSearch: true,
    },
  },
  skud: {
    Базовый: { website: "https://sigur.com" },
    Sigur: { website: "https://sigur.com" },
    Parsec: { website: "https://parsec.ru" },
    PERCo: { website: "https://perco.ru" },
    Biosmart: { website: "https://biosmart.ru" },
    RusGuard: { website: "https://www.rusguard.ru" },
  },
  ssoi: {
    Базовый: { website: "https://trassir.com" },
    TRASSIR: { website: "https://trassir.com" },
    "ISS (Интеллект)": { website: "https://iss.ru" },
    Macroscop: { website: "https://macroscop.com" },
    AxxonSoft: { website: "https://www.axxonsoft.com" },
  },
  aps: {
    Базовый: {
      website: "https://shop.bolid.ru",
      searchPathTemplate: "/search/?q={query}",
      preferSearch: true,
    },
    Болид: {
      website: "https://shop.bolid.ru",
      searchPathTemplate: "/search/?q={query}",
      preferSearch: true,
    },
    Рубеж: {
      website: "https://products.rubezh.ru",
      searchPathTemplate: "/search/?q={query}",
      preferSearch: true,
    },
    "Аргус-Спектр": { website: "https://argus-spectr.ru" },
    Simplex: { website: "https://www.johnsoncontrols.com/fire-detection/simplex" },
    Siemens: { website: "https://www.siemens.com/global/en/products/buildings/fire-safety.html" },
  },
  soue: {
    Базовый: { website: "https://roxton-audio.com" },
    Болид: {
      website: "https://shop.bolid.ru",
      searchPathTemplate: "/search/?q={query}",
      preferSearch: true,
    },
    Рубеж: {
      website: "https://products.rubezh.ru",
      searchPathTemplate: "/search/?q={query}",
      preferSearch: true,
    },
    Roxton: { website: "https://roxton-audio.com" },
  },
};

export function getManufacturerSource(systemType, vendorName) {
  return MANUFACTURER_SOURCES[systemType]?.[vendorName] || { website: "" };
}

export default vendors;
